// <auto-generated />
using EF_Migration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Migration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250903121119_add-office-entity")]
    partial class addofficeentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Migration.Entites.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VarChar");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics",
                            Price = 1000.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics",
                            Price = 2000.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chemistry",
                            Price = 1500.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biology",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Computer Science",
                            Price = 3000.00m
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VarChar");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique()
                        .HasFilter("[OfficeId] IS NOT NULL");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmed Abdullah",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yasmeen Mohammed",
                            OfficeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khalid Hassan",
                            OfficeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nadia Ali",
                            OfficeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Omar Ibrahim",
                            OfficeId = 5
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Office", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VarChar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VarChar");

                    b.HasKey("Id");

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "building A",
                            Name = "Off_05"
                        },
                        new
                        {
                            Id = 2,
                            Location = "building B",
                            Name = "Off_12"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Adminstration",
                            Name = "Off_32"
                        },
                        new
                        {
                            Id = 4,
                            Location = "IT Department",
                            Name = "Off_44"
                        },
                        new
                        {
                            Id = 5,
                            Location = "IT Department",
                            Name = "Off_43"
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Instructor", b =>
                {
                    b.HasOne("EF_Migration.Entites.Office", "office")
                        .WithOne("Instructor")
                        .HasForeignKey("EF_Migration.Entites.Instructor", "OfficeId");

                    b.Navigation("office");
                });

            modelBuilder.Entity("EF_Migration.Entites.Office", b =>
                {
                    b.Navigation("Instructor");
                });
#pragma warning restore 612, 618
        }
    }
}
