// <auto-generated />
using System;
using EF_Migration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Migration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Migration.Entites.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VarChar");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics",
                            Price = 1000.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics",
                            Price = 2000.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chemistry",
                            Price = 1500.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biology",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Computer Science",
                            Price = 3000.00m
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Enrollment", b =>
                {
                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("SectionId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments", (string)null);

                    b.HasData(
                        new
                        {
                            SectionId = 6,
                            StudentId = 1
                        },
                        new
                        {
                            SectionId = 6,
                            StudentId = 2
                        },
                        new
                        {
                            SectionId = 7,
                            StudentId = 3
                        },
                        new
                        {
                            SectionId = 7,
                            StudentId = 4
                        },
                        new
                        {
                            SectionId = 8,
                            StudentId = 5
                        },
                        new
                        {
                            SectionId = 8,
                            StudentId = 6
                        },
                        new
                        {
                            SectionId = 9,
                            StudentId = 7
                        },
                        new
                        {
                            SectionId = 9,
                            StudentId = 8
                        },
                        new
                        {
                            SectionId = 10,
                            StudentId = 9
                        },
                        new
                        {
                            SectionId = 10,
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VarChar");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique()
                        .HasFilter("[OfficeId] IS NOT NULL");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmed Abdullah",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yasmeen Mohammed",
                            OfficeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khalid Hassan",
                            OfficeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nadia Ali",
                            OfficeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Omar Ibrahim",
                            OfficeId = 5
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Office", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VarChar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VarChar");

                    b.HasKey("Id");

                    b.ToTable("Offices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "building A",
                            Name = "Off_05"
                        },
                        new
                        {
                            Id = 2,
                            Location = "building B",
                            Name = "Off_12"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Adminstration",
                            Name = "Off_32"
                        },
                        new
                        {
                            Id = 4,
                            Location = "IT Department",
                            Name = "Off_44"
                        },
                        new
                        {
                            Id = 5,
                            Location = "IT Department",
                            Name = "Off_43"
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("FRI")
                        .HasColumnType("bit");

                    b.Property<bool>("MON")
                        .HasColumnType("bit");

                    b.Property<bool>("SAT")
                        .HasColumnType("bit");

                    b.Property<bool>("SUN")
                        .HasColumnType("bit");

                    b.Property<bool>("THU")
                        .HasColumnType("bit");

                    b.Property<bool>("TUE")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VarChar");

                    b.Property<bool>("WED")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Schedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FRI = false,
                            MON = true,
                            SAT = false,
                            SUN = true,
                            THU = true,
                            TUE = true,
                            Title = "Daily",
                            WED = true
                        },
                        new
                        {
                            Id = 2,
                            FRI = false,
                            MON = false,
                            SAT = false,
                            SUN = true,
                            THU = true,
                            TUE = true,
                            Title = "DayAfterDay",
                            WED = false
                        },
                        new
                        {
                            Id = 3,
                            FRI = false,
                            MON = true,
                            SAT = false,
                            SUN = false,
                            THU = false,
                            TUE = false,
                            Title = "Twice-a-Week",
                            WED = true
                        },
                        new
                        {
                            Id = 4,
                            FRI = true,
                            MON = false,
                            SAT = true,
                            SUN = false,
                            THU = false,
                            TUE = false,
                            Title = "Weekend",
                            WED = false
                        },
                        new
                        {
                            Id = 5,
                            FRI = true,
                            MON = true,
                            SAT = true,
                            SUN = true,
                            THU = true,
                            TUE = true,
                            Title = "Compact",
                            WED = true
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Section", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VarChar");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Sections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            InstructorId = 1,
                            Name = "S_MA1",
                            ScheduleId = 1,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            InstructorId = 2,
                            Name = "S_MA2",
                            ScheduleId = 3,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            InstructorId = 1,
                            Name = "S_PH1",
                            ScheduleId = 4,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            InstructorId = 3,
                            Name = "S_PH2",
                            ScheduleId = 1,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            InstructorId = 2,
                            Name = "S_CH1",
                            ScheduleId = 1,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            InstructorId = 3,
                            Name = "S_CH2",
                            ScheduleId = 2,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            InstructorId = 4,
                            Name = "S_BI1",
                            ScheduleId = 3,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            InstructorId = 5,
                            Name = "S_BI2",
                            ScheduleId = 4,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 5,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            InstructorId = 4,
                            Name = "S_CS1",
                            ScheduleId = 4,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 5,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            InstructorId = 5,
                            Name = "S_CS2",
                            ScheduleId = 3,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 5,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            InstructorId = 4,
                            Name = "S_CS3",
                            ScheduleId = 5,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VarChar");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fatima Ali"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Noor Saleh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Omar Youssef"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Huda Ahmed"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amira Tariq"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zainab Ismail"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Yousef Farid"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Layla Mustafa"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mohammed Adel"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Samira Nabil"
                        });
                });

            modelBuilder.Entity("EF_Migration.Entites.Enrollment", b =>
                {
                    b.HasOne("EF_Migration.Entites.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_Migration.Entites.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EF_Migration.Entites.Instructor", b =>
                {
                    b.HasOne("EF_Migration.Entites.Office", "office")
                        .WithOne("Instructor")
                        .HasForeignKey("EF_Migration.Entites.Instructor", "OfficeId");

                    b.Navigation("office");
                });

            modelBuilder.Entity("EF_Migration.Entites.Section", b =>
                {
                    b.HasOne("EF_Migration.Entites.Course", "course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_Migration.Entites.Instructor", "instructor")
                        .WithMany("Sections")
                        .HasForeignKey("InstructorId");

                    b.HasOne("EF_Migration.Entites.Schedule", "schedule")
                        .WithMany("Sections")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("instructor");

                    b.Navigation("schedule");
                });

            modelBuilder.Entity("EF_Migration.Entites.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("EF_Migration.Entites.Instructor", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("EF_Migration.Entites.Office", b =>
                {
                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EF_Migration.Entites.Schedule", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
